# Generated by Django 4.1.7 on 2023-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Complete', 'Complete')], default='Running', max_length=256)),
            ],
        ),
    ]
